//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendTestDocplanner.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
    internal sealed partial class nuget : global::System.Configuration.ApplicationSettingsBase {
    #pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

        private static nuget defaultInstance = ((nuget)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new nuget())));
        
        public static nuget Default {
            get {
                return defaultInstance;
            }
        }
    }
}
